config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update, :destroy]

  root 'homes#top'
  get '/about' => 'homes#about', as: "about"


  # get '/learns' => 'learns#index', as: "learns"
  # post '/learns' => 'learns#create', as: "learn"
  # get 'learns/:id/eit' => 'learns#edit', as: "edit_learn"
  # patch '/learns/:id/' => 'learns#update', as: "learn"
  # delete '/learns/:id' => 'learns#destroy', as: "learn"
  resources :learns, only: [:index, :create, :edit, :update, :destroy]
  get '/learns/chapter1' => 'learns#chapter1', as: :chapter1
  get '/learns/chapter2' => 'learns#chapter2', as: :chapter2
  get '/learns/chapter3' => 'learns#chapter3', as: :chapter3
  get '/learns/chapter4' => 'learns#chapter4', as: :chapter4
  get '/learns/chapter5' => 'learns#chapter5', as: :chapter5
  get '/learns/chapter6' => 'learns#chapter6', as: :chapter6
  get '/learns/chapter7' => 'learns#chapter7', as: :chapter7
  get '/learns/chapter8' => 'learns#chapter8', as: :chapter8
  get '/learns/chapter9' => 'learns#chapter9', as: :chapter9
  get '/learns/chapter10' => 'learns#chapter10', as: :chapter10
  get '/learns/chapter11' => 'learns#chapter11', as: :chapter11
  get '/learns/chapter12' => 'learns#chapter12', as: :chapter12
  get '/learns/chapter13' => 'learns#chapter13', as: :chapter13
  get '/learns/chapter14' => 'learns#chapter14', as: :chapter14
  get '/learns/chapter15' => 'learns#chapter15', as: :chapter15
  get '/learns/chapter16' => 'learns#chapter16', as: :chapter16
  get '/learns/chapter17' => 'learns#chapter17', as: :chapter17
  get '/learns/chapter18' => 'learns#chapter18', as: :chapter18
  get '/learns/chapter19' => 'learns#chapter19', as: :chapter19
  get '/learns/chapter20' => 'learns#chapter20', as: :chapter20

  resources :works, only: [:index, :create, :update, :destroy] do
    resources  :favorites, only: [:create, :destroy]
  end
  get '/users/:id/favorites' => 'favorites#index', as: :user_favorites

  get '/works/step1' => 'works#step1', as: "works_1"
  get '/works/step2' => 'works#step2', as: "works_2"
  get '/works/step3' => 'works#step3', as: "works_3"
  get '/works/step4' => 'works#step4', as: "works_4"
  get '/works/step' => 'works#step5', as: "works_5"
  get '/works/user_works' => 'works#user_works', as: "user_works"
  get '/works/new_arrivals' => 'works#new_arrivals', as: "user_newArrivals"
  get '/works/ranks' => 'works#ranks', as: "ranks"
  get '/works/user_works/:id' => 'works#user_work', as: "user_work"
end

app/models/learn.rb
class Learn < ApplicationRecord

	belongs_to :user

	validates :memo, presence: true, length: {maximum: 200}
	validates :essential_type, presence: true
	validates :chapter, presence: true
end

app/controllers/learns_controller.rb
class LearnsController < ApplicationController

	before_action :authenticate_user!, only: [:create, :update, :destroy]
	protect_from_forgery

	def index
	end

	def create
		@memo = Learn.new(learn_params)
		if @memo.save
			respond_to do |format|
				format.html { redirect_to request.referer }
				format.json { render json: {memo: @memo.memo,
											id: @memo.id,
											chapter: @memo.chapter,
											essential_type: @memo.essential_type,
											user_id: @memo.user_id
											}
							}
			end
		else
			redirect_to learns_path
		end
	end

	def edit
		@memo = Learn.find(params[:id])
		if @memo.user == current_user
			render :edit
		else
			redirect_to learns_path
		end
	end

	def update
		@memo = Learn.find(params[:id])
		if @memo.update!(learn_params)
			respond_to do |format|
				format.html { redirect_to request.referer }
				format.json { render json: {memo: @memo.memo,
											id: @memo.id
											}
							}
			end
		else
			redirect_to learns_path
		end
	end

	def destroy
		@memo = Learn.find(params[:id])
		if @memo.destroy
			respond_to do |format|
				format.html { redirect_to request.referer }
				format.json { render json: {id: params[:id]} }
			end
		else
			redirect_to learns_path
		end
	end

	def chapter1
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 1).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 1).where(essential_type: 1)
	end

	def chapter2
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 2).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 2).where(essential_type: 1)
	end

	def chapter3
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 3).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 3).where(essential_type: 1)
	end

	def chapter4
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 4).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 4).where(essential_type: 1)
	end

	def chapter5
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 5).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 5).where(essential_type: 1)
	end

	def chapter6
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 6).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 6).where(essential_type: 1)
	end

	def chapter7
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 7).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 7).where(essential_type: 1)
	end

	def chapter8
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 8).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 8).where(essential_type: 1)
	end

	def chapter9
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 9).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 9).where(essential_type: 1)
	end

	def chapter10
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 10).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 10).where(essential_type: 1)
	end

	def chapter11
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 11).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 11).where(essential_type: 1)
	end

	def chapter12
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 12).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 12).where(essential_type: 1)
	end

	def chapter13
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 13).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 13).where(essential_type: 1)
	end

	def chapter14
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 14).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 14).where(essential_type: 1)
	end

	def chapter15
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 15).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 15).where(essential_type: 1)
	end

	def chapter16
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 16).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 16).where(essential_type: 1)
	end

	def chapter17
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 17).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 17).where(essential_type: 1)
	end

	def chapter18
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 18).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 18).where(essential_type: 1)
	end

	def chapter19
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 19).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 19).where(essential_type: 1)
	end

	def chapter20
		@user = current_user
		@memo = Learn.new
		@non_essential_memos = Learn.where(user_id: current_user).where(chapter: 20).where(essential_type: 0)
		@essential_memos = Learn.where(user_id: current_user).where(chapter: 20).where(essential_type: 1)
	end

	private
	def learn_params
		params.require(:learn).permit(:user_id, :essential_type, :chapter, :memo)
	end
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/views/learns/_non_essential.html.erb
<div id="memo<%= non_essential.id %>">
    <div id="js-memo-label-<%= non_essential.id %>" class="non_essential-memo"><%= simple_format(non_essential.memo) %></div>
	<div>
		<p id="js-memo-post-error-<%= non_essential.id %>" class="text-danger"></p>
		<textarea style="display: none" id="js-textarea-memo-<%= non_essential.id %>" class="form-control memo-post-error"><%= non_essential.memo %></textarea>
		<div id="js-memo-button-<%= non_essential.id %>" class="js-right" style="display: none;">
			<button data-cancel-id=<%= non_essential.id %> type="button" class="btn btn-xs btn-light memo-cancel-button">キャンセル</button>
			<button data-update-id=<%= non_essential.id %> type="submit" class="btn btn-xs btn-success memo-update-button">更新</button>
		</div>
		<div id="js-memo-edit-delete-<%= non_essential.id %>" class="pull-right">
			<span data-memo-id=<%= non_essential.id %> class="js-edit-memo-button">
				<i class="fas fa-edit text-success"></i>
			</span>
			<span> / </span>
			<%= link_to learn_path(non_essential), method: :delete, class:"memo_delete" do %>
				<i class="fas fa-trash-alt text-danger"></i>
			<% end %>
		</div>
	</div>
	<br>
	<div class="memo-border_bottom"></div>
</div>

app/views/learns/chapter10.html.erb
<div class="row space_top">
	<div class="col-xs-offset-1 col-xs-11">
		<div class="col-xs-12 chapter-headline">
			<span class="chapter-number">第10章</span>
			<span class="chapter-title">Part3 目標</span>
			<div class="point">
				最終形を明確にする。
			</div>
		</div>
		<div class="col-xs-12 quotations">
			ひとつの目標を、立ち止まらずに追いかける。それが成功の秘訣です。<br>
			アンナ・パヴロワ(バレーダンサー)
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-11 col-xs-offset-1 case-study-box">
		<div class="study-title">〜　ブラッド・ピットとネルソン・マンデラ　〜</div>
		<div class="col-xs-12">
			<div class="col-sm-6 study-item">
				<h3>01</h3>
				<span class="number-title">現実味のない目標</span>
				<span class="number-title_english">Unrealistic goals</span>
				<div class="sentence">
					スタンフォード大学でビル・ミーハンが行った授業の中に「非営利組織の戦略的経営」という授業があった。そのとき与えられた課題のなかに、非営利組織のビジョンおよびミッションステートメントを評価するというものだ。<br>
					100以上もの実例を見ていく中で、壮大だが空虚なステートメントがいかに多いかを思い知らされた。たとえば「世界から飢餓を撲滅する」という壮大な理想。それをわずか5人の組織がそんなことを言っても、現実味がない。
				</div>
			</div>
			<div class="col-sm-6 study-item">
				<h3>02</h3>
				<span class="number-title">心動かされた目標</span>
				<span class="number-title_english">Moved goals</span>
				<div class="sentence">
					そんな中途半端な理想主義が溢れるなかで、ひとつのステートメントが異彩を放っていた。誰でも即座に理解できて、心を動かされる。そのステートメントを書いたのは少し意外な人物だった。俳優で社会起業家のブラッド・ピットだ。<br>
					彼はハリケーン・カトリーナに襲われたニューオリンズの復興の遅さに苛立ち、自らメイク・イット・ライト財団を設立した。その目標はこうだ。「ニューオリンズの下9地区に住む世帯のために、低価格で環境に優しく、災害に強い家を150戸設立する」。このステートメントは、教室の空気を一変させた。具体的でリアル。リアルだが心を動かす。「達成をどうやって判定するのか」の答えも、これ以上ないほど明確だ。
				</div>
			</div>
		</div>
		<div class="col-xs-12">
			<div class="col-sm-6 study-item">
				<h3>03</h3>
				<span class="number-title">本質を見つめた目標</span>
				<span class="number-title_english">Goals that look at the essence</span>
				<div class="sentence">
					ネルソン・マンデラは27年間の獄中生活を通じて、人生の本質を見つめ続けた。1962年に投獄されたとき、マンデラはすべてを奪われた。家も評判も自尊心も、そしてもちろん自由も。<br>
					それからというもの、彼は本質だけを見つめ、そのほかのあらゆるものを切り捨てた。自分の怒りや恨みさえも忘れた。彼が選んだ目標は、「南アフリカにおけるアパルトヘイトの撤廃」だった。
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-offset-1 col-xs-11 border-line"></div>
</div>


<div class="row">
	<div class="col-xs-offset-1 col-xs-11 explanation-box">
		<div class="ex-title">〜　本質を見据えて生きる　〜</div>
		<div class="">
			<div class="col-xs-7 margin_style-2 chapterText ex-textBox ex-right">
				<div class="ex-text">
					<span class="ex-textLarge">重要なこと</span>にエネルギーを集中させるため、不要なものを切り捨てる技術。
					最初に切り捨てるべきは、やろうとしている意図にそぐわない行動だ。
					単純なことのようだが、これを実現するためには、自分がどんな目的に向かっているかを明確に定義しなければならない。
				</div>
			</div>
			<div class="col-xs-offset-5 col-xs-7 margin_style-2 ex-textBox ex-left">
				<div class="ex-text margin_style-1">
					<span class="ex-textLarge">「かなり明確」</span>を「完全に明確」にする。
					あなたの目的や戦略は明確か、と経営者にたずねると「かなり明確です」という答えがよく返ってくる。
					かなり明確なら、それで十分だと思っているようだ。
					だが「完全に明確」な状態を知ると、それまでの「かなり」が不便だったことに気付く。
					まるで視力の悪い人が、初めて眼鏡をかけたときのようなものだ。
				</div>
			</div>
			<div class="col-xs-7 margin_style-2 chapterText ex-textBox ex-right">
				<div class="ex-text margin_style-1">
					<span class="ex-textLarge">どうすれば</span>
					目的を明確にできるのだろうか？<br>
					一つのやり方は「本質目標」を決めることだ。
				</div>
				<div class="ex-text">
					◎ビジョン・ミッション　<刺激的だが具体性に乏しい目標><br>
					　ex--「世界を変えたい」<br><br>
					◎価値観　<平凡で一般的な目標><br>
					　ex--「イノベーション」「リーダーシップ」「チームワーク」<br><br>
					◎四半期目標　<常に具体的だが魅力的ではない目標><br>
					　ex--「昨年比5％の増益」<br><br>
					◎本質目標　<具体的で魅力的な目標><br>
					　ex--「南アフリカにおけるアパルトヘイトの撤廃」
				</div>
				<div class="ex-text honsitu-goal_image"></div>
			</div>
			<div class="col-xs-offset-5 col-xs-7 margin_style-2 ex-textBox ex-left">
				<div class="ex-text margin_style-1">
					<span class="ex-textLarge">本質目標</span>
					は、仕事や会社だけのものではない。正しく使えば、人生に意味を与え、正しい方向へと導いてくれる。人生の本質目標を決めるのは、容易ではない。勇気と洞察力を持ち、自分の力を最高に発揮できる行動を見定めなくてはならない。
				</div>
				<div class="ex-text">
					<span class="ex-textLarge">そのためには</span>
					、タフな問いに答えることが必要だ。トレードオフを直視し、本質から外れたものごとを断固として切り捨てなくてはならない。厳しいが、やるだけの価値はある。本当に明確な目標だけが、自分や組織の力を最大限に引き出し、真にすぐれた成果を可能にしてくれる。
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-offset-1 col-xs-11 border-line"></div>
</div>


<%= render partial: 'memo-area' %>

<% if user_signed_in? %>
	<div class="row">
		<div class="col-xs-1" id="memoBtn">
			<div class="toggle-btn">
				<input type="checkbox" class="cb-value" />
				<span class="round-btn"></span>
			</div>
		</div>
		<%= render partial: 'memo-btn', locals: {memo: @memo, chapter_num: 10} %>
	</div>
<% end %>


<!-- <div class="row">
	<div class="col-lg-offset-1 col-lg-5">
		<div class="row">
			<div class="col-lg-offset-1 col-lg-10 non_essential-contents">
				<h2>非エッセンシャル思考</h2>
				<p class="learn-contents">
					・具体的だが、人の心を動かさない四半期目標
				</p>
				<p class="learn-contents">
					・価値観はあるが、それを実行するための行動規範がない
				</p>
			</div>
		</div>
	</div>
	<div class="col-lg-5">
		<div class="row">
			<div class="col-lg-offset-1 col-lg-10 essential-contents">
				<h2>エッセンシャル思考</h2>
				<p class="learn-contents">
					・具体的かつ魅力的な戦略
				</p>
				<p class="learn-contents">
					・意味があり、心に残る本質目標
				</p>
				<p class="learn-contents">
					・ひとつの決断によって、その後のあらゆる決断を不要にする
				</p>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-offset-1 col-lg-5">
		<div class="row">
			<div class="col-lg-offset-1 col-lg-10 non_essential-memo">
				<div>非エッセンシャル思考メモ蘭<br>
					（自身の経験など振り返り思ったことなど、何でも残しておけます）
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-5">
		<div class="row">
			<div class="col-lg-offset-1 col-lg-10 essential-memo">
				<div>エッセンシャル思考メモ蘭<br>
					（自身の経験など振り返り思ったことなど、何でも残しておけます）
				</div>
			</div>
		</div>
	</div>
</div> -->

<div class="row">
	<div class="col-xs-offset-1 col-xs-11 nav-bar">
		<div>
			<%= link_to "前章", "/learns/chapter9", class:"btn btn-default col-xs-2" %>
		</div>
		<div>
			<%= link_to "一覧", "/learns", class:"btn btn-default col-xs-offset-3 col-xs-2" %>
		</div>
		<div>
			<%= link_to "次章", "/learns/chapter11", class:"btn btn-default col-xs-offset-3 col-xs-2" %>
		</div>
	</div>
</div>

app/views/learns/edit.html.erb
<div class="row">
	<div class="col-xs-offset-3 col-xs-6">
		<h2>メモの編集</h2>
		<% if @memo.essential_type == 0 %>
		    <div class="non-essential">
		    	<%= form_with model: @memo, url: learn_path do |f| %>
				    <div class="form-gorup">
				    	<%= f.label :memo, "非エッセンシャル思考メモ" %><br>
				    	<%= f.text_area :memo, class:"col-xs-12", rows:"4", placeholder: "自身の経験など振り返って感じたことなどメモに残しましょう" %>
				    </div>
				    <%= f.hidden_field :user_id, :value => current_user.id %>
				    <%= f.hidden_field :chapter, :value => @memo.chapter %>
				    <%= f.hidden_field :essential_type, :value => @memo.essential_type %>
				    <br>
				    <%= f.submit "メモを更新", class:"pull-right" %>
				<% end %>
			</div>
		<% else %>
		    <div class="essential">
		    	<%= form_with model: @memo, url: learn_path do |f| %>
				    <div class="form-gorup">
				    	<%= f.label :memo, "エッセンシャル思考メモ" %><br>
				    	<%= f.text_area :memo, class:"col-xs-12", rows:"4", placeholder: "自身の経験など振り返って感じたことなどメモに残しましょう" %>
				    </div>
				    <%= f.hidden_field :user_id, :value => current_user.id %>
				    <%= f.hidden_field :chapter, :value => @memo.chapter %>
				    <%= f.hidden_field :essential_type, :value => @memo.essential_type %>
				    <br>
				    <%= f.submit "メモを更新", class:"pull-right" %>
				<% end %>
			</div>
		<% end %>
	</div>
</div>