config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update, :destroy]

  root 'homes#top'
  get '/about' => 'homes#about', as: "about"


  # get '/learns' => 'learns#index', as: "learns"
  # post '/learns' => 'learns#create', as: "learn"
  # get 'learns/:id/eit' => 'learns#edit', as: "edit_learn"
  # patch '/learns/:id/' => 'learns#update', as: "learn"
  # delete '/learns/:id' => 'learns#destroy', as: "learn"
  resources :learns, only: [:index, :create, :edit, :update, :destroy]
  get '/learns/chapter1' => 'learns#chapter1', as: :chapter1
  get '/learns/chapter2' => 'learns#chapter2', as: :chapter2
  get '/learns/chapter3' => 'learns#chapter3', as: :chapter3
  get '/learns/chapter4' => 'learns#chapter4', as: :chapter4
  get '/learns/chapter5' => 'learns#chapter5', as: :chapter5
  get '/learns/chapter6' => 'learns#chapter6', as: :chapter6
  get '/learns/chapter7' => 'learns#chapter7', as: :chapter7
  get '/learns/chapter8' => 'learns#chapter8', as: :chapter8
  get '/learns/chapter9' => 'learns#chapter9', as: :chapter9
  get '/learns/chapter10' => 'learns#chapter10', as: :chapter10
  get '/learns/chapter11' => 'learns#chapter11', as: :chapter11
  get '/learns/chapter12' => 'learns#chapter12', as: :chapter12
  get '/learns/chapter13' => 'learns#chapter13', as: :chapter13
  get '/learns/chapter14' => 'learns#chapter14', as: :chapter14
  get '/learns/chapter15' => 'learns#chapter15', as: :chapter15
  get '/learns/chapter16' => 'learns#chapter16', as: :chapter16
  get '/learns/chapter17' => 'learns#chapter17', as: :chapter17
  get '/learns/chapter18' => 'learns#chapter18', as: :chapter18
  get '/learns/chapter19' => 'learns#chapter19', as: :chapter19
  get '/learns/chapter20' => 'learns#chapter20', as: :chapter20

  resources :works, only: [:index, :create, :update, :destroy] do
    resources  :favorites, only: [:create, :destroy]
  end
  get '/users/:id/favorites' => 'favorites#index', as: :user_favorites

  get '/works/step1' => 'works#step1', as: "works_1"
  get '/works/step2' => 'works#step2', as: "works_2"
  get '/works/step3' => 'works#step3', as: "works_3"
  get '/works/step4' => 'works#step4', as: "works_4"
  get '/works/step' => 'works#step5', as: "works_5"
  get '/works/user_works' => 'works#user_works', as: "user_works"
  get '/works/new_arrivals' => 'works#new_arrivals', as: "user_newArrivals"
  get '/works/ranks' => 'works#ranks', as: "ranks"
  get '/works/user_works/:id' => 'works#user_work', as: "user_work"
end

app/models/work.rb
class Work < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy

	validates :genre, presence: true
	validates :writing, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

	before_action :authenticate_user!, only: [:create, :update, :destroy]
	protect_from_forgery

	def index
		@works = Work.where(user_id: current_user.id)
	end

	def create
		@work = Work.new(work_params)
		if @work.save
			respond_to do |format|
				format.html {redirect_to request.referer}
				format.json {render json: {
										id: @work.id,
										writing: @work.writing,
										user_id: @work.user_id,
										genre: @work.genre
									}
							}
			end
		else
			redirect_to works_path
		end
	end

	def update
		@work = Work.find(params[:id])
		if @work.update(work_params)
			respond_to do |format|
				format.html { redirect_to request.referer }
				format.json { render json: {
										id: @work.id,
										writing: @work.writing
									}
				}
			end
		else
			redirect_to works_path
		end
	end

	def destroy
		@work = Work.find(params[:id])
		if @work.destroy
			respond_to do |format|
				format.html { redirect_to request.referer }
				format.json { render json: { id: params[:id] } }
			end
		else
			redirect_to works_path
		end
	end


	def step1
		@axis_of_life = Work.new
		@axis_of_lifes = Work.where(user_id: current_user.id).where(genre: 1)
		@most_axis_of_life = Work.find_by(user_id: current_user.id, genre: 2)
	end

	def step2
		@most_axis_of_life = Work.find_by(user_id: current_user.id, genre: 2)
		@essential_goal = Work.new
		@essential_goals = Work.where(user_id: current_user.id).where(genre: 3)
		@my_essential_goal = Work.find_by(user_id: current_user.id, genre: 4)
	end

	def step3
		@my_essential_goal = Work.find_by(user_id: current_user.id, genre: 4)
		@necessary_action = Work.new
		@necessary_actions = Work.where(user_id: current_user.id).where(genre: 5)
	end

	def step4
		@my_essential_goal = Work.find_by(user_id: current_user.id, genre: 4)
		@necessary_actions = Work.where(user_id: current_user.id).where(genre: 5)
		@baby_step = Work.new
		@baby_steps = Work.where(user_id: current_user.id).where(genre: 6)
	end

	def step5
		@baby_steps = Work.where(user_id: current_user.id).where(genre: 6)
		@habit = Work.new
		@habits = Work.where(user_id: current_user.id).where(genre: 7)
		@habit_todo = Work.find_by(user_id: current_user.id, genre: 8)
	end

	PER = 20

	def user_works
		@user_essential_goals = Work.where(genre: 4).order(created_at: :desc).limit(10)
		@all_ranks = Work.find(Favorite.group(:work_id).order('count(work_id) desc').limit(10).pluck(:work_id))
	end

	def new_arrivals
		@new_arrivals = Work.page(params[:page]).per(PER).where(genre: 4).order(created_at: :desc)
	end

	def ranks
		ranks = Work.find(Favorite.group(:work_id).order('count(work_id) desc').pluck(:work_id))
		@ranks = Kaminari.paginate_array(ranks).page(params[:page]).per(PER)
	end

	def user_work
		@user = User.find(params[:id])
		@works = Work.where(user_id: params[:id])
		@essential_goal = @works.find_by(genre: 4)
	end

	private
	def work_params
		params.require(:work).permit(:user_id, :genre, :writing)
	end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/new_arrivals.html.erb
<div class="row space_top">
	<div class="col-xs-offset-1 col-xs-11">
	    <h1 class="work-title">新着一覧</h1>
	</div>

	<div class="col-xs-offset-1 col-xs-11">
		<% @new_arrivals.each do |new_arrival| %>
			<div class="col-xs-6 user_works-box">
                <div class="col-xs-12 margin_style2">
                	<%= link_to user_path(new_arrival.user) do %>
                    	<%= attachment_image_tag new_arrival.user, :profile_image, class: "user-icon", fallback:"no_image.jpg" %>
                    <% end %>
                    <span class="slash-interval"> / </span>
                    <span><%= new_arrival.user.name %></span>
                </div>
		        <div class="col-xs-4">本質目標</div>
		        <div class="col-xs-8">
                    <%= simple_format(new_arrival.writing) %>
                </div>
                <%= link_to user_work_path(new_arrival.user.id)do %>
                    <button class="btn btn-xs btn-default pull-right">もっとみる</button>
                <% end %>
                <div class="border_bottom-line"></div>
	        </div>
		<% end %>
    </div>
    <div class="list-page">
		<%= paginate @new_arrivals %>
	</div>
</div>

app/views/works/noise.html.erb
<div class="row">
	<div class="col-xs-offset-1 col-xs-10">
		<div class="row">
	        <div class="col-xs-1 step-logo">step1</div>
	        <div class="col-xs-offset-2 col-xs-6">
		        <h1 class="work-title">「ノイズ」について振り返る</h1>
		        <p class="work-explanation">
			    ノイズについて日々の生活や今まで、どの程度出来ていたか<br>
			    エッセンシャル思考と非エッセンシャル思考に分けて把握する。
		        </p>
	        </div>
	    </div>

		<div class="row space">
			<div class="col-xs-5">
				<h3 class="non_essential">非エッセンシャル思考</h3>
				<p>
					大多数のものごとが大切だと思い込む<br>
					「全部やらなくては」という思考から抜け出せないなど
				</p>
			</div>
			<div class="col-xs-2">
				<h3 class="step-headline">選択</h3>
			</div>
			<div class="col-xs-5">
				<h3 class="essential">エッセンシャル思考</h3>
				<p>
					大多数のものごとが不要だと考える<br>
					多くのことをやらなくて済むように、多くを吟味するなど
				</p>
			</div>
		</div>

		<div class="row space">
			<div class="col-xs-5">
				<div class="row">
					<div class="non_essential">
						<%= form_with model: @writing, url: works_path do |f| %>
						    <div class="form-group">
						    	<%= f.label :wrting, "「ノイズ」に関する非エッセンシャル思考" %>
						    	<%= f.text_area :writing, class:"col-xs-12 text-black", rows:"4", placeholder: "ご自身の経験を書き込みましょう" %>
						    </div>
						    <%= f.hidden_field :user_id, :value => current_user.id %>
						    <%= f.hidden_field :genre, :value => 2 %>
						    <br>
						    <br>
						    <br>
						    <br>
						    <%= f.submit "作成", class:"text-black pull-right" %>
						<% end %>
					</div>
					<br>
					<% @non_essential_writing.each do |non_essential| %>
			        	<div class="non_essential">
			        		<div><%= non_essential.writing %></div>
			        		<%= link_to "削除", work_path(non_essential), method: :delete, class:"btn btn-danger btn-sm pull-right" %>
			        	</div>
			        	<br>
			        <% end %>
			    </div>
			</div>
			<div class="col-xs-offset-2 col-xs-5">
				<div class="row">
					<div class="essential">
						<%= form_with model: @writing, url: works_path do |f| %>
						    <div class="form-group">
						    	<%= f.label :wrting, "「ノイズ」に関するエッセンシャル思考" %>
						    	<%= f.text_area :writing, class:"col-xs-12", rows:"4", placeholder: "ご自身の経験を書き込みましょう" %>
						    </div>
						    <%= f.hidden_field :user_id, :value => current_user.id %>
						    <%= f.hidden_field :genre, :value => 3 %>
						    <br>
						    <br>
						    <br>
						    <br>
						    <%= f.submit "作成", class:"pull-right" %>
						<% end %>
					</div>
					<br>
			        <% @essential_writing.each do |essential| %>
			        	<div class="essential">
			        		<div><%= essential.writing %></div>
			        		<%= link_to "削除", work_path(essential), method: :delete, class:"btn btn-danger btn-sm pull-right" %>
			        	</div>
			        	<br>
			        <% end %>
			    </div>
			</div>
		</div>

		<div class="row space">
			<%= link_to "戻る", 'javascript:history.back()', class:"col-xs-offset-1 col-xs-2 btn btn-default" %>
			<%= link_to "My Work一覧", works_path, class:"col-xs-offset-2 col-xs-2 btn btn-default" %>
			<%= link_to "次へ", works_3_path, class:"col-xs-offset-2 col-xs-2 btn btn-default" %>
		</div>
	</div>
</div>

app/views/works/ranks.html.erb
<div class="row space_top">
	<div class="col-xs-offset-1 col-xs-11">
	    <h1 class="work-title">ランキング</h1>
	</div>

	<div class="col-xs-offset-1 col-xs-11">
		<% @ranks.each do |rank| %>
			<div class="col-xs-6 user_works-box">
                <div class="col-xs-12 margin_style2">
                	<%= link_to user_path(rank.user) do %>
	                    <%= attachment_image_tag rank.user, :profile_image, class: "user-icon", fallback:"no_image.jpg" %>
	                   <% end %>
                    <span class="slash-interval"> / </span>
                    <span><%= rank.user.name %></span>
                </div>
		        <div class="col-xs-4">本質目標</div>
		        <div class="col-xs-8">
                    <%= simple_format(rank.writing) %>
                </div>
                <%= link_to user_work_path(rank.user.id)do %>
                    <button class="btn btn-xs btn-default pull-right">もっとみる</button>
                <% end %>
                <div class="border_bottom-line"></div>
	        </div>
		<% end %>
    </div>
    <div class="list-page">
		<%= paginate @ranks %>
	</div>
</div>

app/views/works/selection.html.erb
<div class="row">
	<div class="col-xs-offset-1 col-xs-10">
		<div class="row">
	        <div class="col-xs-3 step-logo">step1</div>
	        <div class="col-xs-6">
		        <h1 class="work-title">「選択」について振り返る</h1>
		        <p class="work-explanation">
			    選択について日々の生活や今まで、どの程度出来ていたか<br>
			    エッセンシャル思考と非エッセンシャル思考に分けて把握する。
		        </p>
	        </div>
	    </div>

		<div class="row space">
			<div class="col-xs-5">
				<h3 class="non_essential">非エッセンシャル思考</h3>
				<p>
					自分で選ぶことを少しずつ放棄して、<br>
					いつの間にか誰かのいいなりになるといった経験など
				</p>
			</div>
			<div class="col-xs-2">
				<h3 class="step-headline">選択</h3>
			</div>
			<div class="col-xs-5">
				<h3 class="essential">エッセンシャル思考</h3>
				<p>これをやろうと選んだ経験など</p>
			</div>
		</div>

		<div class="row space">
			<div class="col-xs-5">
				<div class="row">
					<div class="non_essential">
						<%= form_with model: @writing, url: works_path, id:"new_work" do |f| %>
						    <div class="form-group">
						    	<%= f.label :writing, "「選択」に関する非エッセンシャル思考" %>
						    	<%= f.text_area :writing, id:"work_writing", class:"col-xs-12 text-black", rows:"4", placeholder:"ご自身の経験を書き込みましょう" %>
						    </div>
						    <%= f.hidden_field :user_id, :value => current_user.id %>
						    <%= f.hidden_field :genre, :value => 0 %>
						    <br>
						    <br>
						    <br>
						    <br>
						    <%= f.submit "作成", class:"text-black pull-right" %>
						<% end %>
					</div>
					<br>
			        <% @non_essential_writing.each do |non_essential| %>
			             <div class="non_essential work_writings">
			             	<div><%= non_essential.writing %></div>
			             	<%= link_to "削除", work_path(non_essential), method: :delete, class:"btn btn-danger btn-sm pull-right" %>
			             </div>
			             <br>
			        <% end %>
			    </div>
			</div>
			<div class="col-xs-offset-2 col-xs-5">
				<div class="row">
					<div class="essential">
						<%= form_with model: @writing, url: works_path do |f| %>
						    <div class="form-group">
						    	<%= f.label :writing, "「選択」に関するエッセンシャル思考" %>
						    	<%= f.text_area :writing,  class:"col-xs-12", rows:"4", placeholder:"ご自身の経験を書き込みましょう" %>
						    </div>
						    <%= f.hidden_field :user_id, :value => current_user.id %>
						    <%= f.hidden_field :genre, :value => 1 %>
						    <br>
						    <br>
						    <br>
						    <br>
						    <%= f.submit "作成", class:"pull-right" %>
						<% end %>
					</div>
					<br>
			        <% @essential_writing.each do |essential| %>
			             <div class="essential">
			             	<div><%= essential.writing %></div>
			             	<%= link_to "削除", work_path(essential), method: :delete, class:"btn btn-danger btn-sm pull-right" %>
			             </div>
			             <br>
			        <% end %>
			    </div>
			</div>
		</div>

		<div class="row space">
			<%= link_to "My Work一覧", works_path, class:"col-xs-offset-5 col-xs-2 btn btn-default" %>
			<%= link_to "次へ", works_2_path, class:"col-xs-offset-2 col-xs-2 btn btn-default" %>
		</div>
	</div>
</div>

app/views/works/step1.html.erb
<div class="row space_top">
	<div class="col-xs-offset-1 col-xs-11">
		<h1 class="work-title">人生の軸を考える
			<span class="work-number">Step1</span>
		</h1>
        <p class="work-explanation">
		    あなたにとって生きていく上で大切だと感じる<br>
		    「人生の軸」を考えて書き出していきましょう。
	    </p>
	</div>

	<div id="work-lists" class="col-xs-offset-1 col-xs-11 work-display">
		<p class="writing-headline">人生の軸一覧</p>
		<% @axis_of_lifes.each do |axis_of_life| %>
		    <div id="writing<%= axis_of_life.id %>" class="col-xs-6 left-line">
		    	<div id="js-writing-label-<%= axis_of_life.id %>"><%= simple_format(axis_of_life.writing) %></div>
		    	<p id="js-writing-post-error-<%= axis_of_life.id %>" class="text-danger"></p>
		    	<textarea style="display: none;" id="js-textarea-writing-<%= axis_of_life.id %>" class="form-control writing-post-error"><%= axis_of_life.writing %></textarea>
		    	<div id="js-writing-button-<%= axis_of_life.id %>" class="js-right" style="display: none;">
					<button data-cancel-id=<%= axis_of_life.id %> type="button" class="btn btn-xs writing-cancel-button">キャンセル</button>
					<button data-update-id=<%= axis_of_life.id %> type="submit" class="btn btn-xs btn-success writing-update-button">更新</button>
				</div>
				<div id="js-writing-edit-delete-<%= axis_of_life.id %>" class="pull-right">
					<span data-writing-id=<%= axis_of_life.id %> class="js-edit-writing-button">
						<i class="fas fa-edit text-success"></i>
					</span>
					<span> / </span>
					<%= link_to work_path(axis_of_life), method: :delete, class:"writing_delete", data: {confirm: "削除しますか？"} do %>
						<i class="fas fa-trash-alt text-danger"></i>
					<% end %>
				</div>
				<br>
				<div class="writing-border_bottom"></div>
		    </div>
		<% end %>
	</div>

	<!-- テキスト作成エリア -->
	<div class="col-xs-offset-1 col-xs-11 margin_style1">
    	<div class="">
			<%= form_with(model: @axis_of_life, url: works_path, id: "work_input") do |f| %>
				<%= f.label :writing, "人生の軸" %>
		    	<%= f.text_area :writing, id:"writing_input", class:"form-control", rows: "3", placeholder: "自身の大切にしたい「人生の軸」を書き出しましょう。" %>
			    <%= f.hidden_field :user_id, {:value => current_user.id, :id => "user_id_input", :class => "user_id_input"} %>
			    <%= f.hidden_field :genre, {:value => 1, :id => "genre_input", :class => "genre_input"} %>
			    <%= f.submit "作成する", class:"pull-right writing_form-btn" %>
			<% end %>
		</div>
	</div>
	<!-- テキスト作成エリア -->

	<div class="col-xs-offset-1 col-xs-11 work-display margin_style1">
    	<% if Work.where(user_id: current_user.id).exists?(genre: 2) == true %>
	    	<div class="col-xs-6">
	    		<div id="writing<%= @most_axis_of_life.id %>">
		    		<label for="js-textarea-writing-<%= @most_axis_of_life.id %>">最も大切にしたい人生の軸</label>
		    		<div id="js-writing-label-<%= @most_axis_of_life.id %>"><%= simple_format(@most_axis_of_life.writing) %></div>
		    		<p id="js-writing-post-error-<%= @most_axis_of_life.id %>" class="text-danger"></p>
		    		<textarea style="display: none;" id="js-textarea-writing-<%= @most_axis_of_life.id %>" class="form-control writing-post-error"><%= @most_axis_of_life.writing %></textarea>
			    	<div id="js-writing-button-<%= @most_axis_of_life.id %>" class="js-right" style="display: none;">
						<button data-cancel-id=<%= @most_axis_of_life.id %> type="button" class="btn btn-xs writing-cancel-button">キャンセル</button>
						<button data-update-id=<%= @most_axis_of_life.id %> type="submit" class="btn btn-xs btn-success writing-update-button">更新</button>
					</div>
					<div id="js-writing-edit-delete-<%= @most_axis_of_life.id %>" class="pull-right">
						<span data-writing-id=<%= @most_axis_of_life.id %> class="js-edit-writing-button">
							<i class="fas fa-edit text-success">編集</i>
						</span>
						<span> / </span>
						<%= link_to work_path(@most_axis_of_life), method: :delete, data: {confirm: "削除しますか？"} do %>
							<i class="fas fa-trash-alt text-danger">削除</i>
						<% end %>
					</div>
				</div>
			</div>
	    	<div class="col-xs-6">
	    		<%= form_with model: @most_axis_of_life do |f| %>
	    			<%= f.label :writing, "作成した選択肢" %>
		    		<%= f.collection_select(
	    								:writing,
	    								@axis_of_lifes,
	    								:writing,
	    								:writing,
	    								{prompt: "---人生の軸を選び直す---"},
	    								{class: "form-control"})
	    			%>
		    		<%= f.submit "変更する", class:"pull-right" %>
		    	<% end %>
	    	</div>
	    <% else %>
	    	<div class="col-xs-offset-1 col-xs-9 margin_style1">
	    		<p>書き出した中で、あなとにとって最も大切にしたい「人生の軸」を1つ選んでみましょう。</p>
	    		<%= form_with model: @axis_of_life do |f| %>
	    			<%= f.label :writing, "最も大切にしたい人生の軸" %>
	    		    <%= f.collection_select(:writing,
	    		    						@axis_of_lifes,
	    		    						:writing,
	    		    						:writing,
	    		    						{prompt:"---書き出した中から1つ選択して下さい---"},
	    		    						{class: "form-control"})
	    		    %>
	    		    <%= f.hidden_field :user_id, :value => current_user.id %>
	    		    <%= f.hidden_field :genre, :value => 2 %>
	    		    <%= f.submit "決定する", class:"pull-right" %>
	    		<% end %>
	    	</div>
    	<% end %>
    </div>

	<div class="col-xs-offset-1 col-xs-11 margin_style3">
		<%= link_to "My Works", works_path, class:"col-xs-offset-5 col-xs-2 btn btn-default" %>
		<%= link_to "Next Step", works_2_path, class:"col-xs-offset-3 col-xs-2 btn btn-default" %>
	</div>
</div>

app/views/works/user_works.html.erb
<div class="row space_top">
	<div class="col-xs-offset-1 col-xs-11">
	    <h1 class="work-headline">User Works</h1>
        <div class="bottom-line"></div>
	    <p class="headline-explanation">
		他のユーザのWorkを参考にいろいろな考え方・価値観を知ってみましょう。<br>
		"お気に入り"をつけることで、ご自身の「Favorite」からいつでも確認できます。
	    </p>
    </div>

    <div class="col-xs-offset-1 col-xs-11">
    	<div class="col-sm-6">
    	    <div class="user_works-title">新着</div>
            <div class="title-bottom_line"></div>
            <% @user_essential_goals.each do |goal| %>
    	        <div class="row user_works-box">
                    <div class="col-xs-12 margin_style2">
                        <%= link_to user_path(goal.user) do %>
                            <%= attachment_image_tag goal.user, :profile_image, class: "user-icon", fallback:"no_image.jpg" %>
                        <% end %>
                        <span class="slash-interval"> / </span>
                        <span><%= goal.user.name %></span>
                    </div>
    		        <div class="col-xs-4">本質目標</div>
    		        <div class="col-xs-8">
                        <%= simple_format(goal.writing) %>
                    </div>
                    <%= link_to user_work_path(goal.user.id)do %>
                        <button class="btn btn-xs btn-default pull-right">もっとみる</button>
                    <% end %>
                </div>
                <div class="border_bottom-line"></div>
            <% end %>
            <div class="list-page margin_style1">
                <%= link_to "新着一覧", user_newArrivals_path, class: " btn back-color-gray btn-md btn-secondary" %>
            </div>
        </div>
        <div class="col-sm-6">
    	    <div class="user_works-title">ランキング</div>
            <div class="title-bottom_line"></div>
            <% @all_ranks.each.with_index(1) do |work, i| %>
                <div class="row user_works-box">
                    <div class="col-xs-4 rank_number"><%= i %>位</div>
                    <div class="col-xs-8 margin_style2">
                        <%= attachment_image_tag work.user, :profile_image, class: "user-icon", fallback:"no_image.jpg" %>
                        <span class="slash-interval"> / </span>
                        <span><%= work.user.name %></span>
                    </div>
        		    <div class="col-xs-4">本質目標</div>
        		    <div class="col-xs-8"><%= simple_format(work.writing) %></div>
                    <%= link_to user_work_path(work.user.id) do %>
                        <button class="btn btn-xs btn-default pull-right">もっとみる</button>
                    <% end %>
                </div>
                <div class="border_bottom-line"></div>
            <% end %>
            <div class="list-page">
                <%= link_to "ランキング一覧", ranks_path, class: " btn back-color-gray btn-md" %>
            </div>
        </div>
    </div>
</div>