config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update, :destroy]

  root 'homes#top'
  get '/about' => 'homes#about', as: "about"


  # get '/learns' => 'learns#index', as: "learns"
  # post '/learns' => 'learns#create', as: "learn"
  # get 'learns/:id/eit' => 'learns#edit', as: "edit_learn"
  # patch '/learns/:id/' => 'learns#update', as: "learn"
  # delete '/learns/:id' => 'learns#destroy', as: "learn"
  resources :learns, only: [:index, :create, :edit, :update, :destroy]
  get '/learns/chapter1' => 'learns#chapter1', as: :chapter1
  get '/learns/chapter2' => 'learns#chapter2', as: :chapter2
  get '/learns/chapter3' => 'learns#chapter3', as: :chapter3
  get '/learns/chapter4' => 'learns#chapter4', as: :chapter4
  get '/learns/chapter5' => 'learns#chapter5', as: :chapter5
  get '/learns/chapter6' => 'learns#chapter6', as: :chapter6
  get '/learns/chapter7' => 'learns#chapter7', as: :chapter7
  get '/learns/chapter8' => 'learns#chapter8', as: :chapter8
  get '/learns/chapter9' => 'learns#chapter9', as: :chapter9
  get '/learns/chapter10' => 'learns#chapter10', as: :chapter10
  get '/learns/chapter11' => 'learns#chapter11', as: :chapter11
  get '/learns/chapter12' => 'learns#chapter12', as: :chapter12
  get '/learns/chapter13' => 'learns#chapter13', as: :chapter13
  get '/learns/chapter14' => 'learns#chapter14', as: :chapter14
  get '/learns/chapter15' => 'learns#chapter15', as: :chapter15
  get '/learns/chapter16' => 'learns#chapter16', as: :chapter16
  get '/learns/chapter17' => 'learns#chapter17', as: :chapter17
  get '/learns/chapter18' => 'learns#chapter18', as: :chapter18
  get '/learns/chapter19' => 'learns#chapter19', as: :chapter19
  get '/learns/chapter20' => 'learns#chapter20', as: :chapter20

  resources :works, only: [:index, :create, :update, :destroy] do
    resources  :favorites, only: [:create, :destroy]
  end
  get '/users/:id/favorites' => 'favorites#index', as: :user_favorites

  get '/works/step1' => 'works#step1', as: "works_1"
  get '/works/step2' => 'works#step2', as: "works_2"
  get '/works/step3' => 'works#step3', as: "works_3"
  get '/works/step4' => 'works#step4', as: "works_4"
  get '/works/step' => 'works#step5', as: "works_5"
  get '/works/user_works' => 'works#user_works', as: "user_works"
  get '/works/new_arrivals' => 'works#new_arrivals', as: "user_newArrivals"
  get '/works/ranks' => 'works#ranks', as: "ranks"
  get '/works/user_works/:id' => 'works#user_work', as: "user_work"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Essentialism</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/fff3ba2388.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/scrollreveal"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid space_bottom">
      <div class="col-xs-12 header">
        <div class="col-xs-4 title">Essentialism</div>
          <% if user_signed_in? %>
            <div class="col-xs-7 header-menu">
              <ul>
                <li><%= link_to "Learns", learns_path %></li>
                <li>/</li>
                <li><%= link_to "My Works", works_path %></li>
                <li>/</li>
                <li><%= link_to "User Works", user_works_path %></li>
                <li>/</li>
                <li><%= link_to "Favorites", user_favorites_path(current_user.id) %></li>
              </ul>
            </div>
            <div class="header_user-icon">
              <%= link_to user_path(current_user) do %>
                <%= attachment_image_tag current_user, :profile_image, fallback: "no_image.jpg" %>
              <% end %>
            </div>
          <% else %>
          <div class="col-xs-7 header-menu">
              <ul>
                <li><%= link_to "Top", root_path %></li>
                <li>/</li>
                <li><%= link_to "About", about_path %></li>
                <li>/</li>
                <li><%= link_to "Log in", new_user_session_path %></li>
                <li>/</li>
                <li><%= link_to "Sign in", new_user_registration_path %></li>
                <li>/</li>
                <li><%= link_to "Learns", learns_path %></li>
              </ul>
            </div>
            <div class="header_user-icon">ようこそ<br>” ゲスト様 ”</div>
        <% end %>
        <!-- ハンバーガーメニュー -->
        <div id="hm-icon">
          <a class="menu-trigger" href="#">
            <span></span>
            <span></span>
            <div class="menu-text">MENU</div>
          </a>
        </div>
        <div id="sp-menu">
          <nav>
            <h1>MENU</h1>
            <% if user_signed_in? %>
              <ul>
                <li><%= link_to "My Page", user_path(current_user.id) %></li>
                <li><%= link_to "Learns", learns_path %></li>
                <li><%= link_to "My Works", works_path %></li>
                <li><%= link_to "User Works", user_works_path %></li>
                <li><%= link_to "Favorites", user_favorites_path(current_user.id) %></li>
                <li><%= link_to "Top", root_path %></li>
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            <% else %>
              <ul>
                <li><%= link_to "Sign in", new_user_registration_path %></li>
                <li><%= link_to "Log in", new_user_session_path %></li>
                <li><%= link_to "Learns", learns_path %></li>
                <li><%= link_to "About", about_path %></li>
              </ul>
            <% end %>
          </nav>
        </div>
        <!-- ハンバーガメニュー -->
      </div>

      <!-- ↓fixedの余白を埋めるbox↓ -->
      <!-- <div class="row">
        <div class="space_top"></div>
      </div> -->

      <%= yield %>
    </div>

    <div class="footer"> ©2021/Essentialism/All Rigth Reserved</div>

  </body>
</html>